#!/bin/bash

#1. Скрипт upback
#a. Скрипт должен скопировать в каталог /home/user/restore/ все файлы из актуального на  данный момент каталога резервного копирования (имеющего в имени наиболее свежую дату), за исключением файлов с предыдущими версиями.

restore="/home/natalem/restore"

backup=$(find ~/ -maxdepth 1 -type d -name Backup-* | sort -r | head -1)

if [[ ! -d $restore ]]; then
	mkdir $restore
fi

find "$backup" -type f |
grep -E --invert-match "[0-9]{4}-[0-9]{2}-[0-9]{2}$" |
while read line; do
	filename=$(echo "$line" | grep -Eo '[^\/]*$') 
	cp "$line" "$restore/$filename"
done
